### ISSUE TITLE
Fur Shader

### ISSUE THREAD

**Issue by zauberparacelsus** [luboslenco/lue#13]
Would it be possible to implement add a fur shader as a feature in zBlend?  I'm not talking the about the customized particle simulation that blender uses, but rather a material or shader that simulates the appearance of fur.  The technique is also useful for simulating grass.

An example GLSL fur shader can be found here: https://github.com/sdao/fur-demo

**Comment by luboslenco** [comment]
Absolutely! It is possible to create a custom renderer which uses a custom shader, so any technique should be doable.

Any usage for this that you have in mind?

**Comment by zauberparacelsus** [comment]
Yeah, putting fur onto character models.

**Comment by luboslenco** [comment]
Im currently experimenting with stand-alone editor which imports data from Blender but does other stuff on it's own. Will probably transform ZBlend into this sooner or later, and then look to improve renderer and include various shaders like you suggested. Might take a while but it already supports running the game live directly in editor, which would not be otherwise possible. It can also run in web browser, which could be nice for getting started or previewing scenes.

![](https://pbs.twimg.com/media/CL4rFpYUMAEOdIt.png:large)

**Comment by luboslenco** [comment]
Moving here: https://github.com/luboslenco/cyclesgame/issues/6
