### ISSUE TITLE
zBlend file missing?

### ISSUE THREAD

**Issue by zauberparacelsus** [luboslenco/lue#15]
Following the installation instructions at http://zblend.org/docs/ I found an error.  When I hit the Start button under the zblend_start section, I get an error saying that the file ./Libraries/zblend/blender/zblend_assets.py does not exist.

This was running with Blender 2.74 under 64bit Windows 8.1

**Comment by Mixerman123** [comment]
Yah same issue.

I read it and it is because everything was renamed and is now broken. I have literally no idea why it was renamed, zblend was fine iMHO. All the links in the file structure and online seem broken.

Kinda annoyed at this as I wanted to start using 3D with haxe. Let's hope the author is able to fix this up so we can have a nice 3D lib :)

**Comment by zauberparacelsus** [comment]
Gonna close this one, since zBlend was split into Lue and CyclesGame
